import type { Metadata } from 'next';
import { Poppins, Aboreto } from 'next/font/google';
import './globals.css';
import ApolloProviderWrapper from '@/Providers/ApolloProvider';
import Header from '@/components/Header/Header';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400', '700'],
});

const aboreto = Aboreto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-aboreto',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${aboreto.variable}`}>
        <ApolloProviderWrapper>
          <Header />
          {children}
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
